/** Display titles of the Issues page lists, shared by the lists and their counts. */
export const ISSUE_TITLES = {
	dd4: "In DD4",
	justAddedQuestionnaires: "Just Added Questionnaires",
	pausedClients: "Paused Clients",
	evaluationInProcess: "Evaluation In Process",
	missingAppointments: "Appointments to be Created",
	autismStops: "Autism Stops",
	punchlistNotInDb: "Punchlist Clients Not In DB",
	punchlistInactive: "Punchlist Clients Inactive",
	punchlistDuplicateIds: "Duplicate Punchlist IDs",
	noReferralSource: "No Referral Source",
	missingDistricts: "Missing Districts",
	poorAddressLookup: "Poor Address Lookup",
	babyNetAgeOut: "Too Old for BabyNet",
	notInTA: "Not in TA",
	dropList: "Drop List",
	notesOnly: "Notes Only",
	noDriveIds: "No Drive IDs",
	possiblePrivatePay: "Potential Private Pay",
	unreviewedRecords: "Unreviewed/Unreceived Records",
	charterSchoolConfirm: "Charter School Awaiting Confirmation",
	insuranceMismatch: "Insurance Doesn't Match",
	duplicateDriveFolders: "Duplicate Drive Folders",
	duplicateQuestionnaireLinks: "Clients with Duplicate Questionnaire Links",
	sharedQuestionnaires: "Clients Sharing Questionnaires",
	duplicateNames: "Duplicate Client Names",
	partialBatteries: "Partial Questionnaire Batteries",
} as const;
