services:
  winnonah:
    restart: no
    image: ghcr.io/driftwoodeval/winnonah:latest@sha256:b002c35f47dc8521fa194236f99a65fa1571e2a5f42c3f3f2270955ce4665fd8
    container_name: winnonah
    environment:
      - DATABASE_URL=${DOCKER_DATABASE_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_TRUST_HOST=true
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - AUTH_URL=${AUTH_URL}
      - PUNCHLIST_ID=${PUNCHLIST_ID}
      - PUNCHLIST_RANGE=${PUNCHLIST_RANGE}
      - REDIS_HOST=${DOCKER_REDIS_HOST}
      - OPENPHONE_API_TOKEN=${OPENPHONE_API_TOKEN}
      - OPENPHONE_NUMBER_ID=${OPENPHONE_NUMBER_ID}
      - API_KEY=${API_KEY}
      - NEXT_PUBLIC_APP_TITLE=${NEXT_PUBLIC_APP_TITLE}
      - NEXT_PUBLIC_APP_DOMAIN=${NEXT_PUBLIC_APP_DOMAIN}
      - PY_API=${DOCKER_PY_API}

    volumes:
      - ./logs:/app/logs
      - ../qs/logs/screenshots:/app/q-screenshots

  driftwood-db:
    image: mysql@sha256:c11782aa2a96624c1efc121768641d96954faa136d6aa82751b032d8c426ffbc
    container_name: driftwood-db
    restart: no
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - winnonah_db-data:/var/lib/mysql

  redis:
    image: redis:alpine@sha256:09160599abd229764c0fb44cb6be640294e1d360a54b19985ab4843dcf2d90f1
    container_name: redis-winnonah
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest@sha256:12ff5c6992a9863db4da270746af7c244bcaee49353039af8104268a18d6c4f0
    container_name: cloudflared-winnonah
    command: tunnel --no-autoupdate run --token
      ${CF_TOKEN}
    restart: no

  winnonah-python:
    image: ghcr.io/driftwoodeval/winnonah-python:latest@sha256:686e3e33ff513fb2ba5f748a9072f94de5a0d340e8c6b9e573af623cb5d1aa95
    container_name: winnonah-python
    restart: always
    environment:
      - HEADLESS=true
      - DATABASE_URL=${DOCKER_DATABASE_URL}
      - PUNCHLIST_ID=${PUNCHLIST_ID}
      - PUNCHLIST_RANGE=${PUNCHLIST_RANGE}
      - TA_USERNAME=${TA_USERNAME}
      - TA_PASSWORD=${TA_PASSWORD}
      - EXCLUDED_TA=${EXCLUDED_TA}
      - ASANA_TOKEN=${ASANA_TOKEN}
      - ASANA_WORKSPACE=${ASANA_WORKSPACE}
      - CENSUS_API_KEY=${CENSUS_API_KEY}
      - GEOCODIO_API_KEY=${GEOCODIO_API_KEY}
      - OPENPHONE_API_TOKEN=${OPENPHONE_API_TOKEN}
      - OPENPHONE_NUMBER_ID=${OPENPHONE_NUMBER_ID}
      - OPENPHONE_SIGNING_SECRET=${OPENPHONE_SIGNING_SECRET}
      - OPENPHONE_GREETER_NUMBER_ID=${OPENPHONE_GREETER_NUMBER_ID}
      - OPENPHONE_GREETER_SIGNING_SECRET=${OPENPHONE_GREETER_SIGNING_SECRET}
      - GREETER_SCHEDULE_SHEET_ID=${GREETER_SCHEDULE_SHEET_ID}
      - FAX_FOLDER_ID=${FAX_FOLDER_ID}
      - BASE_FOLDER_ID=${BASE_FOLDER_ID}
      - ERROR_EMAILS=${ERROR_EMAILS}
    volumes:
      - ./python/auth_cache:/app/auth_cache
      - ./python/temp:/app/temp
      - ./python/logs:/app/logs
      - ./python/shapefiles:/app/shapefiles
      - ./python/cache:/app/cache

  watchtower:
    image: containrrr/watchtower@sha256:6dd50763bbd632a83cb154d5451700530d1e44200b268a4e9488fefdfcf2b038
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    restart: always

volumes:
  winnonah_db-data:
