import { logger } from "~/lib/logger";
import { db } from "~/server/db";
import { auditLogs } from "~/server/db/schema";

/**
 * Most mutation inputs carry the client they act on as a top-level `clientId`
 * field, since that's the convention used across the routers. Falls back to
 * null (not every action is client-specific, e.g. role or settings changes).
 */
export function extractClientId(rawInput: unknown): number | null {
	if (
		typeof rawInput === "object" &&
		rawInput !== null &&
		"clientId" in rawInput
	) {
		const clientId = (rawInput as { clientId: unknown }).clientId;
		if (typeof clientId === "number") return clientId;
	}
	return null;
}

/**
 * Records the mutation's submitted input verbatim, including values, since
 * an audit trail that only names which fields changed can't show what
 * actually happened. Access to the log is restricted to the
 * settings:audit-log:view permission, so this relies on that gate rather
 * than on omitting the data.
 */
export function serializeAuditInput(rawInput: unknown) {
	if (rawInput === undefined) return null;
	return rawInput;
}

/**
 * Sentinel userId/userEmail for audit rows generated by server-to-server
 * calls (the `questionnaires` app hitting the internal API) rather than a
 * signed-in user, so they still show up in the same Settings > Audit Log
 * view instead of only in each service's own log files.
 */
export const INTERNAL_API_ACTOR = {
	userId: "system:internal-api",
	userEmail: "questionnaires (internal API)",
};

export async function recordInternalApiAudit(entry: {
	action: string;
	clientId: number | null;
	success: boolean;
	errorMessage?: string;
	ip: string;
}) {
	try {
		await db.insert(auditLogs).values({
			userId: INTERNAL_API_ACTOR.userId,
			userEmail: INTERNAL_API_ACTOR.userEmail,
			action: entry.action,
			clientId: entry.clientId,
			detail: { ip: entry.ip },
			success: entry.success,
			errorMessage: entry.errorMessage ?? null,
		});
	} catch (err) {
		logger.error({ err }, "Failed to write internal API audit log");
	}
}
